server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

# App Properties
example:
  app:
    jwtSecret: MultiTenancySecretKey$1
    jwtExpirationMs: 30000000

springdoc:
  version: 'v1.0'